### ISSUE TITLE
allow snippets not only in html files

### ISSUE THREAD

**Issue by aheinze** [xXiNiXx1/atom-uikit#2]
Hi,

I'm one of the Uikit developers. Thank you very much for this great package. Is it possible to support also other source files than html (e.g. .php etc)

thanks,
artur

**Comment by xXiNiXx1** [comment]
Thank you for your suggestion, I've added support for PHP. Try upgrading to 1.2.0

**Comment by aheinze** [comment]
awesome, thanks :+1:
