### ISSUE TITLE
UIkit Docs

### ISSUE THREAD

**Issue by malles** [xXiNiXx1/atom-uikit#3]
Hi,
The plugin looks great, thanks for that. I wanted to add the plugin to the UIkit docs, just wanted to make sure you're OK with that.

**Comment by xXiNiXx1** [comment]
Ofcourse! That would be great!

**Comment by malles** [comment]
https://github.com/uikit/uikit/commit/79c800114c5958f7bed11879d2fe2295f05a30c2 
Done!
